/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  PortfolioLedger,
  PortfolioLedgerInterface,
} from "../PortfolioLedger";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "TradeExecuted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "recordTrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "trades",
    outputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tradesCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610323806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80631e6c598e146100465780635932c02c146100915780638561a597146100a2575b600080fd5b610059610054366004610276565b6100b7565b604080516001600160a01b039687168152959094166020860152928401919091526060830152608082015260a0015b60405180910390f35b600054604051908152602001610088565b6100b56100b03660046102ab565b610104565b005b600081815481106100c757600080fd5b6000918252602090912060059091020180546001820154600283015460038401546004909401546001600160a01b03938416955091909216929085565b6040805160a0810182526001600160a01b03868116808352868216602080850182815285870189815260608088018a8152426080808b01918252600080546001810182559080529a516005909b027f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563810180549c8c166001600160a01b03199d8e1617905595517f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5648701805491909b169b169a909a1790985591517f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e56584015590517f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e56683015594517f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e567909101558551928352820152928301859052820183905233917f3fcfb2f2e0146d5be7268f9e4cd3c4c0ce3428f68805db227b7fc378db7519ac910160405180910390a250505050565b60006020828403121561028857600080fd5b5035919050565b80356001600160a01b03811681146102a657600080fd5b919050565b600080600080608085870312156102c157600080fd5b6102ca8561028f565b93506102d86020860161028f565b9396939550505050604082013591606001359056fea2646970667358221220e7b4f0854f8d591f8dfb2ea8604265487e44c9e1f33b3ec27c9c60fdb87c223d64736f6c63430008180033";

type PortfolioLedgerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PortfolioLedgerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PortfolioLedger__factory extends ContractFactory {
  constructor(...args: PortfolioLedgerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PortfolioLedger & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PortfolioLedger__factory {
    return super.connect(runner) as PortfolioLedger__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PortfolioLedgerInterface {
    return new Interface(_abi) as PortfolioLedgerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PortfolioLedger {
    return new Contract(address, _abi, runner) as unknown as PortfolioLedger;
  }
}
